/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

public void mixmode(GDropList source, GEvent event) { //_CODE_:mode:708016:
  //println("mod - GDropList >> GEvent." + event + " @ " + millis());
} //_CODE_:mode:708016:

public void instrument(GDropList source, GEvent event) { //_CODE_:instrus:213590:
  //println("dropList1 - GDropList >> GEvent." + event + " @ " + millis());
} //_CODE_:instrus:213590:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setCursor(ARROW);
  surface.setTitle("CG Project");
  mode = new GDropList(this, 659, 9, 129, 168, 7);
  mode.setItems(loadStrings("list_708016"), 0);
  mode.addEventHandler(this, "mixmode");
  instrus = new GDropList(this, 505, 8, 139, 132, 5);
  instrus.setItems(loadStrings("list_213590"), 0);
  instrus.addEventHandler(this, "instrument");
}

// Variable declarations 
// autogenerated do not edit
GDropList mode; 
GDropList instrus; 
